access_token_lifetime: 600
jwt_secret: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
jwt_alg: "HS256"
enabled_scopes:
  - name: "test_scope"
    description: "this is test scope for testing purposes"
  - name: "other_test_scope"
    description: "Another one test scope"
iss: 'https://auth.cmm.ru/'
origins:
  - "https://localhost"
  - "http://localhost"
  - "https://localhost:8000"
  - "http://localhost:8000"
  - "https://localhost:8080"
  - "http://localhost:8080"
supported_pkce:
  - S256
  - plain